2024-02-27T11:04:26,814 Using pip 23.3.1 from /Users/ricopicone/anaconda3/envs/systems/lib/python3.12/site-packages/pip (python 3.12)
2024-02-27T11:04:26,814 Non-user install because site-packages writeable
2024-02-27T11:04:26,857 Created temporary directory: /private/var/folders/x4/vfx1c1xx25b6cqb4pd_jkqhm0000gn/T/pip-build-tracker-g40zsito
2024-02-27T11:04:26,857 Initialized build tracking at /private/var/folders/x4/vfx1c1xx25b6cqb4pd_jkqhm0000gn/T/pip-build-tracker-g40zsito
2024-02-27T11:04:26,857 Created build tracker: /private/var/folders/x4/vfx1c1xx25b6cqb4pd_jkqhm0000gn/T/pip-build-tracker-g40zsito
2024-02-27T11:04:26,857 Entered build tracker: /private/var/folders/x4/vfx1c1xx25b6cqb4pd_jkqhm0000gn/T/pip-build-tracker-g40zsito
2024-02-27T11:04:26,857 Created temporary directory: /private/var/folders/x4/vfx1c1xx25b6cqb4pd_jkqhm0000gn/T/pip-install-y9qv3iwy
2024-02-27T11:04:26,857 ERROR: You must give at least one requirement to install (see "pip help install")
2024-02-27T11:04:26,857 Exception information:
2024-02-27T11:04:26,857 Traceback (most recent call last):
2024-02-27T11:04:26,857   File "/Users/ricopicone/anaconda3/envs/systems/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
2024-02-27T11:04:26,857     status = run_func(*args)
2024-02-27T11:04:26,857              ^^^^^^^^^^^^^^^
2024-02-27T11:04:26,857   File "/Users/ricopicone/anaconda3/envs/systems/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
2024-02-27T11:04:26,857     return func(self, options, args)
2024-02-27T11:04:26,857            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-27T11:04:26,857   File "/Users/ricopicone/anaconda3/envs/systems/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 342, in run
2024-02-27T11:04:26,857     reqs = self.get_requirements(args, options, finder, session)
2024-02-27T11:04:26,857            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-27T11:04:26,857   File "/Users/ricopicone/anaconda3/envs/systems/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 461, in get_requirements
2024-02-27T11:04:26,857     raise CommandError(
2024-02-27T11:04:26,857 pip._internal.exceptions.CommandError: You must give at least one requirement to install (see "pip help install")
2024-02-27T11:04:26,897 Remote version of pip: 24.0
2024-02-27T11:04:26,897 Local version of pip:  23.3.1
2024-02-27T11:04:26,918 Was pip installed by pip? False
2024-02-27T11:04:26,918 Removed build tracker: '/private/var/folders/x4/vfx1c1xx25b6cqb4pd_jkqhm0000gn/T/pip-build-tracker-g40zsito'
